version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev
    expose:
      - 3000
    ports:
      - "3000:3000"

  metateam_academy_mysql_node:
    build: ./docker/mysql
    container_name: 'metateam_academy_mysql_node'
    volumes:
      - ./docker/mysql/logs:/var/log/mysql # コンテナのログを同期
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306" # ポートマッピングを修正
volumes:
  db-store:
